# Create a Pod named multi-container-pod that runs two 
# containers: nginx and busybox. The nginx container should serve web content, 
# and the busybox container should run a script that logs "Hello from Busybox" 
# every 5 seconds.

apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx
    image: nginx
  - name: busybox
    image: busybox
    command: ["sh" , "-c", "while true ; do echo Hello from Busybox ; sleep 5; done"]
